 BucketRoleDataSync:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - datasync.amazonaws.com
          Action:
            - "sts:AssumeRole"
        Description: Role to provide access to datasync
        Policies:
          - PolicyName: EmbeddedInlinePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "s3:GetBucketLocation"
                    - "s3:ListBucket"
                    - "s3:ListBucketMultipartUploads"
                  Effect: Allow
                  Resource: !Sub arn:aws:s3:::${S3BucketPGbadger}
                - Action:
                    - "s3:AbortMultipartUpload"
                    - "s3:DeleteObject"
                    - "s3:GetObject"
                    - "s3:GetObjectTagging"
                    - "s3:ListMultipartUploadParts"
                    - "s3:PutObject"
                    - "s3:PutObjectTagging"
                  Effect: Allow
                  Resource: !Sub arn:aws:s3:::${S3BucketPGbadger}/*
      Tags:
        - Key: Project
          Value: pgBadger
        - Key: Category
          Value: iam
        - Key: Stage
          Value: presenter
        - Key: Name
          Value: !Sub "${AWS::StackName}-BucketRoleDataSync"